### ISSUE TITLE
Compilation errors

### ISSUE THREAD

**Issue by kagiannis** [nauful/NLZM#2]
The ERROR message
```
nl.cpp: In function ‘void RANS::init_cdf(int16 (&)[num_syms])’:
nl.cpp:255:19: error: ‘scale_bits’ was not declared in this scope
    cdf[i] = (i << scale_bits) / num_syms;
                   ^~~~~~~~~~
nl.cpp:255:19: note: suggested alternative: ‘scale_max’
    cdf[i] = (i << scale_bits) / num_syms;
                   ^~~~~~~~~~
                   scale_max
nl.cpp: In function ‘uint32 crc32_calc(const byte*, int64, uint64)’:
nl.cpp:3318:24: error: cast from ‘const byte*’ {aka ‘const unsigned char*’} to ‘byte’ {aka ‘unsigned char’} loses precision [-fpermissive]
  while (n && (byte(next) & 15)) {
                        ^
```

I removed `init_cdf` and replaced `next` with `*next` for it to work.

Also it would be nice if you didn't use windows only stuff like `#include <intrin.h>`.
There are possibly other windows only stuff.
I crosscompiled it to windows and the run it using wine in linux.

**Comment by nauful** [comment]
*next will not align correctly (trying to align pointer, not value). init_cdf is not used anymore, clang++ and MSVC ignored it (no template usage).

Take a look now, made a few small changes to compile on LUbuntu with clang++ and tested that it works correctly.

**Comment by kagiannis** [comment]
Now works OK. Thank you
