### ISSUE TITLE
Critical error in nlzm.cpp, can't compile.

### ISSUE THREAD

**Issue by kekmacska** [nauful/NLZM#4]
Visual Studio 2022 identified that an identifier "ftello64" is not defined, at line 1713. Build failing.

Severity	Code	Description	Project	File	Line	Suppression State	Details
Error (active)	E0020	identifier "ftello64" is undefined	nlzm		1713

**Comment by nauful** [comment]
Apologies for the late response, I missed this earlier. I compiled with clang++, but for MSVC support you can use _ftello64 instead of ftello64.
